server:
  port: 9000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.75.217.205:3306/live_tool?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
