server:
  port: 9000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lyp19891117
    url: jdbc:mysql://106.12.137.47:3306/security?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
